version: "3"

services:
  frontend:
    build:
      context: ./docker/frontend
      dockerfile: Dockerfile
    container_name: nextjs_container
    environment:
      - DB_CONTAINER_NAME=${DB_CONTAINER_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
    ports:
      # Next.js
      - "3000:3000"
      # Storybook
      - "6006:6006"
    volumes:
      - ".:/home/node/workspace"
      - "frontend_node_modules:/home/node/workspace/app/frontend/node_modules"
    working_dir: /home/node/workspace/app/frontend
    tty: true
    stdin_open: true
    
  backend:
    build:
      context: ./docker/backend
      dockerfile: Dockerfile
    container_name: nestjs_container
    ports:
      # Nestjs
      - "3005:3005"
      # prisma studio
      - "5555:5555"
    environment:
      - DB_CONTAINER_NAME=${DB_CONTAINER_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
      # - REDIS_USER=${REDIS_USER}
      # - REDIS_PASSWORD=${REDIS_PASSWORD}
      # - REDIS_HOST=${REDIS_HOST}
      # - REDIS_PORT=${REDIS_PORT}
      # - REDIS_SECRET=${REDIS_SECRET}
    volumes:
      - ".:/home/node/workspace"
      - "backend_node_modules:/home/node/workspace/app/backend/node_modules"
    working_dir: /home/node/workspace/app/backend
    tty: true
    stdin_open: true

  test:
    build:
      context: .
      dockerfile: docker/test/Dockerfile
    container_name: playwright_container
    environment:
      - DB_CONTAINER_NAME=${DB_CONTAINER_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
    ports:
      # Playwright/Report
      - "9323:9323"
    volumes:
      - ".:/home/node/workspace"
      - "test_node_modules:/home/node/workspace/app/test/node_modules"
    working_dir: /home/node/workspace/app/test
    tty: true
    stdin_open: true

  db:
    build:
      context: .
      dockerfile: docker/db/Dockerfile
    container_name: postgres_container
    ports:
    # postgres
    - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
    restart: always

  # redis:
  #   build:
  #     context: .
  #     dockerfile: docker/redis/Dockerfile
  #   container_name: redis_container
  #   ports:
  #     - "6379:6379"


volumes:
  frontend_node_modules:
  backend_node_modules:
  test_node_modules: