version: "3"

services:
  frontend:
    build:
      context: .
      dockerfile: docker/frontend/Dockerfile
    container_name: nextjs_container
    environment:
      - DB_CONTAINER_NAME=${DB_CONTAINER_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
    ports:
      # Next.js
      - "3000:3000"
    volumes:
      - "./app/frontend:/home/node/nextjs"
    tty: true
    stdin_open: true
    
  backend:
    build:
      context: .
      dockerfile: docker/backend/Dockerfile
    container_name: nestjs_container
    ports:
      # Nestjs
      - "3005:3005"
      # prisma studio
      - "5555:5555"
    environment:
      - DB_CONTAINER_NAME=${DB_CONTAINER_NAME}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
    volumes:
      - "./app/backend:/home/node/nestjs"
    tty: true
    stdin_open: true

  db:
    build:
      context: .
      dockerfile: docker/db/Dockerfile
    container_name: postgres_container
    ports:
    # postgres
    - "5432:5432"
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PORT=${POSTGRES_PORT}
    restart: always

  redis:
    build:
      context: .
      dockerfile: docker/redis/Dockerfile
    container_name: redis_container
    ports:
      - "6379:6379"